/**
 * itemstats.js -- classical item analysis.
 * ---------------------------------------------------------------------------
 * The second surface of the tool: turn the lens back on the test itself.
 *
 * Once you have the full response matrix, the psychometric quality of each
 * question is computable, and it is computed here rather than generated by a
 * language model -- these are established statistics, not opinions.
 *
 *   Difficulty (p)        proportion answering correctly. Near 1.0 means the
 *                         item separates nobody.
 *   Discrimination (r)    corrected point-biserial: correlation between getting
 *                         this item right and the student's score on *all the
 *                         other* items. Excluding the item itself matters --
 *                         the uncorrected version is inflated because the item
 *                         contributes to its own total. Low r means strong and
 *                         weak students answered alike, so the item measured
 *                         nothing. Negative r means it measured backwards.
 *   Dead distractor       an option almost nobody selected, which contributes
 *                         no information and effectively shortens the item.
 *
 * Rules of thumb used for flagging follow standard classroom item-analysis
 * practice: r >= 0.30 good, 0.15-0.30 marginal, < 0.15 not discriminating.
 */

import { correctIndex } from './pack.js';
import { posteriorWithout, PARAMS } from './infer.js';

function pearson(x, y) {
  const n = x.length;
  const mx = x.reduce((a, b) => a + b, 0) / n;
  const my = y.reduce((a, b) => a + b, 0) / n;
  let num = 0, dx = 0, dy = 0;
  for (let i = 0; i < n; i++) {
    const a = x[i] - mx, b = y[i] - my;
    num += a * b; dx += a * a; dy += b * b;
  }
  const den = Math.sqrt(dx * dy);
  return den === 0 ? 0 : num / den;
}

/**
 * @returns {Array} one record per item, in item order.
 */
export function analyseItems(pack, responses, inference = null) {
  const ITEMS = pack.items;
  const nStudents = responses.length;
  const ci = ITEMS.map(correctIndex);
  const scored = responses.map(row => row.map((c, i) => (c === ci[i] ? 1 : 0)));
  const totals = scored.map(r => r.reduce((a, b) => a + b, 0));

  return ITEMS.map((item, i) => {
    const col = scored.map(r => r[i]);
    const rest = totals.map((t, s) => t - col[s]);       // rest score: total minus this item
    const p = col.reduce((a, b) => a + b, 0) / nStudents;
    const r = pearson(col, rest);

    const counts = item.opts.map((_, oi) =>
      responses.reduce((n, row) => n + (row[i] === oi ? 1 : 0), 0)
    );
    // Blanks match no option, so they drop out of the counts naturally. Track
    // them explicitly: an item a third of the class skipped is telling you
    // something, and its option shares will not sum to 100% without this.
    const omitted = responses.reduce((n, row) => n + (row[i] == null || row[i] < 0 ? 1 : 0), 0);
    const options = item.opts.map((o, oi) => ({
      index: oi,
      text: o.t,
      correct: !!o.c,
      mis: o.mis || null,
      count: counts[oi],
      share: counts[oi] / nStudents,
      dead: !o.c && counts[oi] / nStudents < 0.03
    }));

    // How concentrated is the item's diagnostic signal? An item can have poor
    // *global* discrimination and still be extremely useful, if its wrong
    // answers pile onto one misconception-mapped option. That is a diagnostic
    // item doing diagnostic work rather than ranking work, and flagging it as
    // "bad" would be a mistake -- so it is separated out explicitly below.
    const diagnosticShare = Math.max(0, ...options.filter(o => o.mis).map(o => o.share));
    const chance = 1 / item.opts.length;

    // Does this item agree with the rest of the test?
    //
    // Counting how many students chose a diagnostic distractor has almost no
    // statistical power at classroom sample sizes: a misconception held by a
    // quarter of 28 students is roughly 7 responses, which is not separable
    // from uniform noise by any per-item test.
    //
    // So ask a better-powered question instead. Take the students who chose
    // this item's main diagnostic distractor, and check whether the *rest of
    // the test* independently says they hold that misconception. High
    // agreement means the item is measuring what it claims to. Low agreement
    // means its wrong answers are landing on students with no corresponding
    // pattern anywhere else, which is what a broken or ambiguous item looks
    // like.
    //
    // The posterior used here has this item's own contribution subtracted out,
    // so the item is not permitted to vote on its own validity.
    let modelAgreement = null;
    let agreementN = 0;
    let signalMis = null;

    if (inference) {
      const top = options.filter(o => o.mis && o.count > 0)
        .sort((a, b) => b.count - a.count)[0];
      if (top) {
        signalMis = top.mis;
        const mIndex = inference.misIds.indexOf(top.mis);
        const chosers = responses
          .map((row, s) => (row[i] === top.index ? s : -1))
          .filter(s => s >= 0);
        agreementN = chosers.length;
        if (agreementN >= 3 && mIndex >= 0) {
          // The test asks whether the remaining items provide *net positive
          // evidence*, not whether they independently clear 50%. With each
          // misconception probed by only two items, removing one leaves a
          // single item behind, and a single item can never clear an absolute
          // threshold -- that is the whole premise of the inference model. The
          // right question for the evidence that survives is directional: does
          // it push the probability above the prior, or below it?
          const agreeing = chosers.filter(s =>
            posteriorWithout(inference, s, mIndex, item.id) > PARAMS.prior).length;
          modelAgreement = agreeing / agreementN;
        }
      }
    }

    const flags = [];
    if (p >= 0.93) flags.push({ kind: 'no-information', text: `${Math.round(p * 100)}% answered correctly, so the item separates nobody.` });
    // A low mean score is only evidence of a problem when the item also fails
    // to separate students. A hard item that strong students get right and weak
    // students get wrong is doing its job, however low the class average is --
    // so difficulty near chance is reported only alongside weak discrimination.
    if (p <= chance + 0.06 && r < 0.15) flags.push({ kind: 'at-chance', text: `${Math.round(p * 100)}% correct against ${Math.round(chance * 100)}% for pure guessing, with no discrimination to offset it -- responses are indistinguishable from random.` });
    if (r < 0) flags.push({ kind: 'negative-discrimination', text: `Discrimination is negative (r = ${r.toFixed(2)}): stronger students did worse on it than weaker ones.` });
    else if (r < 0.15) flags.push({ kind: 'no-discrimination', text: `Discrimination is ${r.toFixed(2)}: your strongest and weakest students answered it alike.` });

    // An item whose wrong answers are mapped to nothing, and on which the class
    // is performing at chance, produces neither a ranking nor a diagnosis. That
    // is a different failure from poor discrimination and is worth naming
    // separately, because the remedy is different: rewrite the options so the
    // wrong ones mean something.
    // "At chance" is a statistical claim, so test it as one rather than picking
    // a cutoff: is the observed proportion correct distinguishable from
    // guessing at this class size? The standard error shrinks as the class
    // grows, so the same rule stays honest for a class of 12 and a class of 300.
    const chanceSe = Math.sqrt((chance * (1 - chance)) / nStudents);
    const zAboveChance = chanceSe > 0 ? (p - chance) / chanceSe : 0;
    const indistinguishableFromGuessing = zAboveChance < 1.64;

    if (diagnosticShare === 0 && indistinguishableFromGuessing && r < 0.30) {
      flags.push({ kind: 'uninformative', text: `None of this item's wrong answers correspond to a known misconception, and ${Math.round(p * 100)}% correct is not statistically distinguishable from guessing at ${Math.round(chance * 100)}% (z = ${zAboveChance.toFixed(2)}). It yields neither a ranking nor a diagnosis.` });
    }

    if (omitted / nStudents >= 0.20) flags.push({ kind: 'skipped', text: Math.round((omitted / nStudents) * 100) + '% of the class left this blank, which usually means it ran long, sat past a time limit, or read as unanswerable.' });

    const dead = options.filter(o => o.dead);
    if (dead.length) flags.push({ kind: 'dead-distractor', text: `${dead.length} option${dead.length > 1 ? 's were' : ' was'} chosen by almost nobody (${dead.map(o => `"${o.text}"`).join(', ')}), so the item is effectively shorter than it looks.` });

    // Classify.
    //
    // The ordering here is the whole argument. Point-biserial discrimination
    // asks "did students who did well overall also get this right", which
    // presumes the test measures one underlying trait. A diagnostic instrument
    // deliberately does not: an item targeting a misconception held by one
    // subgroup will be answered wrongly by that subgroup regardless of their
    // ability elsewhere, and so it can correlate weakly -- or negatively --
    // with total score while being the most informative item on the page.
    //
    // So concentration is checked *before* the correlation verdict. An item
    // whose wrong answers pile onto one misconception is diagnosing. Only an
    // item that fails to discriminate *and* whose errors are scattered across
    // untagged slips is actually broken.
    const concentrated = modelAgreement !== null && modelAgreement >= 0.6;
    const lowDiscrim = r < 0.15;

    // Severity also matters. A dead distractor is a cosmetic defect -- the item
    // still works, one of its options is just wasted -- and grouping it with
    // items that measure nothing would bury the findings that matter.
    const serious = flags.filter(f => f.kind !== 'dead-distractor');

    let quality;
    if (p >= 0.93) quality = 'weak';                       // separates nobody, whatever else is true
    else if (concentrated && lowDiscrim) quality = 'diagnostic';
    else if (r < 0) quality = 'broken';
    else if (serious.length) quality = 'weak';
    else if (flags.length) quality = 'minor';
    else quality = r >= 0.3 ? 'strong' : 'ok';

    const note = quality === 'diagnostic'
      ? `Correlation with total score is ${r.toFixed(2)}, which on an ability test would look bad. It is not. Of the ${agreementN} students who chose "${options.find(o => o.mis === signalMis && o.count > 0)?.text ?? ''}", ${Math.round(modelAgreement * 100)}% are independently diagnosed with ${signalMis} by the rest of the test. This item is diagnosing rather than ranking, and should be kept.`
      : null;

    return {
      id: item.id,
      index: i,
      stem: item.stem,
      topic: item.topic,
      difficulty: p,
      discrimination: r,
      diagnosticShare,
      omitted,
      modelAgreement,
      agreementN,
      signalMis,
      options,
      flags,
      quality,
      note
    };
  });
}

/**
 * Items worth showing the teacher first, worst offenders leading.
 * Diagnostic items are deliberately excluded: they carry flags, but they are
 * not defects.
 */
const FLAG_SEVERITY = {
  'no-information': 3,      // measured nothing at all
  'uninformative': 3,       // no ranking and no diagnosis
  'negative-discrimination': 2,
  'at-chance': 2,
  'no-discrimination': 1,   // marginal: often just a small sample
  'skipped': 2,
  'dead-distractor': 0
};

/** Highest severity among an item's flags. */
export function severityOf(item) {
  return item.flags.reduce((m, f) => Math.max(m, FLAG_SEVERITY[f.kind] ?? 0), 0);
}

export function problemItems(stats) {
  return stats
    .filter(s => s.flags.length && (s.quality === 'broken' || s.quality === 'weak'))
    .sort((a, b) => (severityOf(b) - severityOf(a)) || (a.discrimination - b.discrimination));
}

/** Items that look weak on the usual statistics but are actually diagnostic. */
export function diagnosticItems(stats) {
  return stats.filter(s => s.quality === 'diagnostic')
    .sort((a, b) => b.diagnosticShare - a.diagnosticShare);
}

/**
 * Whole-instrument reliability: Cronbach's alpha over the scored matrix.
 *
 * Read with care. Alpha measures internal consistency under the assumption
 * that every item taps one common trait. This instrument is deliberately
 * multidimensional -- twelve unrelated misconceptions -- so a *low* alpha is
 * the expected result and is evidence that the items are measuring different
 * things, which is the design intent. It is not evidence the test is bad.
 * `interpretAlpha` says so rather than leaving the number to be misread.
 */
export function cronbachAlpha(pack, responses) {
  const ITEMS = pack.items;
  const ci = ITEMS.map(correctIndex);
  const scored = responses.map(row => row.map((c, i) => (c === ci[i] ? 1 : 0)));
  const k = ITEMS.length;
  const n = responses.length;

  const itemVar = ITEMS.map((_, i) => {
    const col = scored.map(r => r[i]);
    const m = col.reduce((a, b) => a + b, 0) / n;
    return col.reduce((s, v) => s + (v - m) ** 2, 0) / n;
  });
  const totals = scored.map(r => r.reduce((a, b) => a + b, 0));
  const mt = totals.reduce((a, b) => a + b, 0) / n;
  const totalVar = totals.reduce((s, v) => s + (v - mt) ** 2, 0) / n;

  if (totalVar === 0) return 0;
  return (k / (k - 1)) * (1 - itemVar.reduce((a, b) => a + b, 0) / totalVar);
}

/** Plain-language reading of an alpha value for a multidimensional instrument. */
export function interpretAlpha(alpha) {
  if (alpha >= 0.8) {
    return `${alpha.toFixed(2)} -- high. The items are behaving as though they measure one common skill, which for a misconception inventory suggests the distractors are not separating distinct errors as intended.`;
  }
  if (alpha >= 0.5) {
    return `${alpha.toFixed(2)} -- moderate. Some shared variance across items, some independent misconception signal.`;
  }
  return `${alpha.toFixed(2)} -- low, and appropriately so. Alpha assumes a single underlying trait; this instrument targets twelve distinct misconceptions, so low internal consistency is evidence of multidimensionality rather than of an unreliable test.`;
}

/** Items with only cosmetic defects (a wasted option), worth a second pass. */
export function minorItems(stats) {
  return stats.filter(s => s.quality === 'minor');
}
